
set(ADD_PHOENIX_APP_ARGUMENTS_OPTIONS)
set(ADD_PHOENIX_APP_ARGUMENTS_ONE ANDROID_KEYSTORE_PROPERTIES_FILE
                                  ANDROID_MANIFEST ANDROID_VERSION_NAME ANDROID_VERSION_CODE
                                  PROPERTIES_TARGET_NAME APP_NAME ANDROID_APK_NAME
                                  MACOS_CERT MACOS_PROVISION_PROFILE
                                  MACOS_APP_ICON_2X MACOS_APP_ICON_3X
                                  MACOS_IPAD_APP_ICON MACOS_IPAD_APP_ICON_2X MACOS_IPAD_PRO_APP_ICON_2X)
set(ADD_PHOENIX_APP_ARGUMENTS_MULTI RESOURCES IPA_RESOURCES LIBRARIES JARS ANDROID_PERMISSIONS
                                    FRAMEWORKS MACOS_PLIST_PROPERTIES MACOS_XCENT_PROPERTIES
                                    SEARCH_PATHS)

