##
# Copyright IBM Corporation 2016,2017
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
# http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.
##

# Dockerfile to build a Docker image with the Swift tools and binaries and
# its dependencies.

FROM ibmcom/swift-ubuntu:4.2
MAINTAINER IBM Swift Engineering at IBM Cloud
LABEL Description="A Swift Ubuntu (v14.04) Docker image with the latest Swift binaries and its dependencies."

# Make user root
USER root

# Expose default port for Kitura
EXPOSE 8080
